### ISSUE TITLE
Lidar com possíveis erros de parseamento e mostrar relatório com os erros encontrados

### ISSUE THREAD

**Issue by mrcosta** [DadosAbertosDeFeira/leis-municipais#6]
Alguns exemplos de como o parser pode falhar atualmente:

* leitura e escrita de arquivos
* não encontrar alguma tag html esperada (provavelmente existem alguns edge cases ainda não tratados no parser)

Caso alguma desses cenários aconteça o parser pararia imediatamente a sua execução. A idéia é tratar melhor esses cenários que podem falhar de maneira a somente registrar o erro, mas ainda assim conseguir parser os arquivos remanescentes e gerar um relatório simples com a relação de arquivos parseado e a lista de falhas encontradas.

**Comment by anapaulagomes** [comment]
Resumo da execução:

```
Erros:

Resumo não encontrado no arquivo /home/ana/test.html

Total de arquivos: 8982

Resumo da execução:
```

| Diretório        | Total           | Parseados  | Com Erro |
| ------------- |:-------------:| -----:| -----:|
| Decretos      | 890 | 800 | 90 |
| Resoluções   | 765  |   765 | 0 |
| Leis Ordinárias | 6.573  |  6.572 | 1 |

```
Tempo de execução: 187 segundos
```
